#       Copyright 2017 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


########################################################################################
## Configuration for deploying Trader microservice using WebSphere Liberty helm chart
########################################################################################

image:
  # Docker Hub with basic registry sign in
  repository: ibmstocktrader/trader
  tag: basicregistry
  # IBM Cloud Private
  #repository: mycluster.icp:8500/stock-trader/trader
  #tag: latest
  # IBM Container Service
  #repository: registry.ng.bluemix.net/stock_trader/trader
  #tag: latest
  pullPolicy: Always
  extraEnvs:
    - name: JWT_AUDIENCE
      valueFrom:
        secretKeyRef:
          name: jwt 
          key: audience
    - name: JWT_ISSUER
      valueFrom:
        secretKeyRef:
          name: jwt
          key: issuer
    - name: OIDC_NAME
      valueFrom:
        secretKeyRef:
          name: oidc
          key: name
          optional: true
    - name: OIDC_ISSUER
      valueFrom:
        secretKeyRef:
          name: oidc
          key: issuer
          optional: true
    - name: OIDC_AUTH
      valueFrom:
        secretKeyRef:
          name: oidc
          key: auth
          optional: true
    - name: OIDC_TOKEN
      valueFrom:
        secretKeyRef:
          name: oidc
          key: token
          optional: true
    - name: OIDC_ID
      valueFrom:
        secretKeyRef:
          name: oidc
          key: id
          optional: true
    - name: OIDC_SECRET
      valueFrom:
        secretKeyRef:
          name: oidc
          key: secret
          optional: true
    - name: OIDC_KEY
      valueFrom:
        secretKeyRef:
          name: oidc
          key: key
          optional: true
    - name: OIDC_NODEPORT
      valueFrom:
        secretKeyRef:
          name: oidc
          key: nodeport
          optional: true

resourceNameOverride: stock-trader

pod:
  labels:
    solution: stock-trader
    version: v1

service:
  enabled: true
  name: trader-service
  port: 9443
  targetPort: 9443
  type: NodePort
  extraPorts:
    - name: trader-service-http
      protocol: TCP
      port: 9080
      targetPort: 9080

ingress:
  enabled: true 
  path: "/trader"
  annotations: 
    #kubernetes.io/ingress.class: "istio"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    #ingress.kubernetes.io/app-root: "/trader"
    #nginx.ingress.kubernetes.io/app-root: "/trader"
    #ingress.kubernetes.io/rewrite-target: /trader
    #nginx.ingress.kubernetes.io/rewrite-target: /trader

monitoring:
  enabled: true